#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_NONE 0
#define ERROR_UNSPECIFIC 1
#define ERROR_MEMORY_ALLOCATION 2
#define ERROR_LOCK_FAILED 3
#define ERROR_DESTRUCTION_PENDING 4

#define REQUEST_ERROR_BASE 10
#define NETWORK_ERROR_BASE 20
#define TASK_SCHEDULE_ERROR_BASE 30
#define SESSION_ERROR_BASE 40
#define DATAPROXY_ERROR_BASE 50

typedef int error_t;

#endif
