#include "fileio.h"
#include "logger.h"
#include "password.h"
#include "utils.h"

#include "settings_manager.h"

#define PASSWORD_FILENAME "xprc_password.cfg"
#define SETTINGS_FILENAME "xprc_settings.cfg"

settings_manager_t* create_settings_manager(char *directory) {
    settings_manager_t *settings_manager = zalloc(sizeof(settings_manager_t));
    if (!settings_manager) {
        return NULL;
    }

    settings_manager->settings = create_settings();
    if (!settings_manager->settings) {
        goto error;
    }

    settings_manager->password_filepath = dynamic_sprintf("%s%c%s", directory, DIRECTORY_SEPARATOR, PASSWORD_FILENAME);
    if (!settings_manager->password_filepath) {
        goto error;
    }

    settings_manager->settings_filepath = dynamic_sprintf("%s%c%s", directory, DIRECTORY_SEPARATOR, SETTINGS_FILENAME);
    if (!settings_manager->settings_filepath) {
        goto error;
    }

    if (mtx_init(&settings_manager->mutex, mtx_plain | mtx_recursive) == thrd_success) {
        return settings_manager;
    }

    error:
    if (settings_manager->settings_filepath) {
        free(settings_manager->settings_filepath);
    }
    if (settings_manager->password_filepath) {
        free(settings_manager->password_filepath);
    }
    if (settings_manager->settings) {
        destroy_settings(settings_manager->settings);
    }
    free(settings_manager);
    return NULL;
}

error_t destroy_settings_manager(settings_manager_t *settings_manager) {
    error_t err = ERROR_NONE;

    if (!settings_manager) {
        return ERROR_NONE;
    }

    err = lock_settings_manager(settings_manager);
    if (err != ERROR_NONE) {
        return err;
    }

    settings_manager->destruction_pending = true;
    unlock_settings_manager(settings_manager);

    // lock & unlock once more to make sure every thread had a chance to notice pending destruction
    if (mtx_lock(&settings_manager->mutex) != thrd_success) {
        RCLOG_WARN("failed to lock settings manager mutex during destruction; continuing regardless");
    } else {
        mtx_unlock(&settings_manager->mutex);
    }

    destroy_settings(settings_manager->settings);
    settings_manager->settings = NULL;

    if (settings_manager->password_filepath) {
        free(settings_manager->password_filepath);
        settings_manager->password_filepath = NULL;
    }

    if (settings_manager->settings_filepath) {
        free(settings_manager->settings_filepath);
        settings_manager->settings_filepath = NULL;
    }

    mtx_destroy(&settings_manager->mutex);

    free(settings_manager);

    return ERROR_NONE;
}

error_t lock_settings_manager(settings_manager_t *settings_manager) {
    if (!settings_manager) {
        return ERROR_UNSPECIFIC;
    }

    if (settings_manager->destruction_pending) {
        return ERROR_DESTRUCTION_PENDING;
    }

    if (mtx_lock(&settings_manager->mutex) != thrd_success) {
        return ERROR_MUTEX_FAILED;
    }

    if (!settings_manager->destruction_pending) {
        return ERROR_NONE;
    }

    unlock_settings_manager(settings_manager);
    return ERROR_DESTRUCTION_PENDING;
}

void unlock_settings_manager(settings_manager_t *settings_manager) {
    if (!settings_manager) {
        return;
    }

    mtx_unlock(&settings_manager->mutex);
}

error_t configure_settings_manager_from_storage(settings_manager_t *settings_manager) {
    error_t err = ERROR_NONE;
    error_t out_err = ERROR_NONE;

    err = lock_settings_manager(settings_manager);
    if (err != ERROR_NONE) {
        return err;
    }

    bool settings_file_exists = check_file_exists(settings_manager->settings_filepath);
    bool password_file_exists = check_file_exists(settings_manager->password_filepath);

    bool failed_settings_load = false;
    bool failed_settings_save = false;
    bool failed_password_load = false;
    bool failed_password_save = false;
    bool is_password_valid = false;

    bool is_first_initialization = (!settings_file_exists && !password_file_exists);
    if (is_first_initialization) {
        err = save_settings_without_password(settings_manager->settings, settings_manager->settings_filepath);
        if (err != ERROR_NONE) {
            RCLOG_WARN("settings manager failed to save settings to %s: %d", settings_manager->settings_filepath, err);
            failed_settings_save = true;
        }
    } else {
        err = load_settings_without_password(settings_manager->settings, settings_manager->settings_filepath);
        if (err != ERROR_NONE) {
            RCLOG_WARN("settings manager failed to load settings from %s: %d", settings_manager->settings_filepath, err);
            failed_settings_load = true;
        }
    }

    bool should_regenerate_password = settings_manager->settings->auto_regen_password;
    if (should_regenerate_password) {
        // password has already been generated by default initialization but still needs to be saved
        err = save_password(settings_manager->settings, settings_manager->password_filepath);
        if (err != ERROR_NONE) {
            RCLOG_WARN("settings manager failed to save password to %s: %d", settings_manager->password_filepath, err);
            failed_password_save = true;
        }
    } else {
        err = load_password(settings_manager->settings, settings_manager->password_filepath);
        if (err != ERROR_NONE) {
            RCLOG_WARN("settings manager failed to load password from %s: %d", settings_manager->password_filepath, err);
            failed_password_load = true;
        }
    }

    is_password_valid = validate_password(settings_manager->settings->password);

    unlock_settings_manager(settings_manager);

    if (failed_settings_load) {
        return SETTINGS_MANAGER_ERROR_SETTINGS_REVERTED;
    } else if (!is_password_valid) {
        return SETTINGS_MANAGER_ERROR_PASSWORD_INVALID;
    } else if (failed_password_load) {
        return SETTINGS_MANAGER_ERROR_PASSWORD_NOT_LOADED;
    } else if (failed_settings_save) {
        return SETTINGS_MANAGER_ERROR_SETTINGS_NOT_SAVED;
    } else if (failed_password_save) {
        return SETTINGS_MANAGER_ERROR_PASSWORD_NOT_SAVED;
    } else if (is_first_initialization) {
        return SETTINGS_MANAGER_ERROR_NO_PREVIOUS_SETTINGS;
    } else {
        return ERROR_NONE;
    }
}

error_t persist_settings_from_manager(settings_manager_t *settings_manager) {
    error_t err = ERROR_NONE;
    error_t out_err = ERROR_NONE;

    err = lock_settings_manager(settings_manager);
    if (err != ERROR_NONE) {
        return err;
    }

    err = save_password(settings_manager->settings, settings_manager->password_filepath);
    if (err != ERROR_NONE) {
        RCLOG_WARN("settings manager failed to save password to %s: %d", settings_manager->password_filepath, err);
        out_err = err;
    }

    err = save_settings_without_password(settings_manager->settings, settings_manager->settings_filepath);
    if (err != ERROR_NONE) {
        RCLOG_WARN("settings manager failed to save settings to %s: %d", settings_manager->settings_filepath, err);
        out_err = err;
    }

    unlock_settings_manager(settings_manager);

    return out_err;
}

error_t copy_settings_to_manager(settings_manager_t *settings_manager, settings_t *settings, bool copy_password) {
    error_t err = ERROR_NONE;
    error_t out_err = ERROR_NONE;

    // only copy valid passwords, indicate error if invalid but continue
    if ((copy_password == SETTINGS_COPY_PASSWORD) && !validate_password(settings->password)) {
        out_err = SETTINGS_MANAGER_ERROR_PASSWORD_INVALID;
        copy_password = SETTINGS_KEEP_PASSWORD;
    }

    err = lock_settings_manager(settings_manager);
    if (err != ERROR_NONE) {
        return err;
    }

    err = copy_settings(settings_manager->settings, settings, copy_password);
    if (err != ERROR_NONE) {
        out_err = err;
    }

    unlock_settings_manager(settings_manager);

    return out_err;
}

error_t copy_settings_from_manager(settings_manager_t *settings_manager, settings_t *settings, bool copy_password) {
    error_t err = ERROR_NONE;

    err = lock_settings_manager(settings_manager);
    if (err != ERROR_NONE) {
        return err;
    }

    err = copy_settings(settings, settings_manager->settings, copy_password);

    unlock_settings_manager(settings_manager);

    return err;
}
