#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_NONE 0
#define ERROR_UNSPECIFIC 1
#define ERROR_MEMORY_ALLOCATION 2
#define ERROR_LOCK_FAILED 3

#define REQUEST_ERROR_BASE 10
#define NETWORK_ERROR_BASE 20
#define TASK_SCHEDULE_ERROR_BASE 30

typedef int error_t;

#endif
